##################
# Active plugins #
##################
plugins:
  - jekyll-feed #Optionals plugins from here
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache

############
# Generics #
############
language: en
title: Matteo Comisso
email: matteo@mcomisso.me
description: >
  A small collection of thoughts, ideas and software experiments from an iOS software developer perspective.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://mcomisso.me
twitter_username: teomatteo89
github_username:  mcomisso

############
# SEO SPECIFIC
twitter:
  username: teomatteo89
  card: summary
social:
  name: Matteo Comisso
  links:
    - https://github.com/mcomisso
    - https://twitter.com/teomatteo89
    - https://facebook.com/100003457918621
    - https://linkedin.com/mcomisso
    - https://keybase.io/mcomisso

about:
  services:
    -
      name: "github"
      url: "https://github.com/mcomisso"
    -
      name: "twitter"
      url: "https://twitter.com/teomatteo89"
    -
      name: "facebook"
      url: "https://facebook.com/100003457918621"
    -
      name: "linkedin" 
      url: "https://linkedin.com/mcomisso"
    -
      name: keybase
      url: https://keybase.io/mcomisso

# Permalinks
permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->

###############
# Site params #
###############
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

theme: jekyll-theme-hacker

highlighter: rouge

google_analytics: UA-NNNNNNNN-N

# Files to exclude, generic
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - package.json
  - post.py

show_excerpts: enabled