##################
# Active plugins #
##################
plugins:
  - jekyll-feed #Optionals plugins from here
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  - jekyll-include-cache

############
# Generics #
############
language: en
url: "http://mcomisso.me"
title: "Matteo Comisso"
email: matteo.comisso@me.com
description: >- # this means to ignore newlines until "baseurl:"
  iOS software developer living in London. 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://mcomisso.me
twitter_username: teomatteo89
github_username:  mcomisso
social_username: teomatteo89

############
# SEO SPECIFIC
twitter:
  username: teomatteo89
author:
  name: Matteo
  url: http://mcomisso.me
  twitter: teomatteo89
social:
  links: ["https://github.com/mcomisso", "https://twitter.com/teomatteo89", "https://facebook.com/100003457918621", "https://linkedin.com/mcomisso", "https://plus.google.com/u/0/+Matteocomisso", "https://medium.com/@mcomisso"]

about:
  name: "Matteo Comisso"
  email: "matteo.comisso@me.com"
  uri: "https://twitter.com/teomatteo89"
  bio: ""
  services:
    -
      name: "github"
      username: "mcomisso"
      url: "https://github.com/mcomisso"
    -
      name: "twitter"
      username: "teomatteo89"
      url: "https://twitter.com/teomatteo89"
    -
      name: "facebook"
      username: "matteocomisso"
      url: "https://facebook.com/100003457918621"
    -
      name: "linkedin"
      username: "mcomisso"
      url: "https://linkedin.com/mcomisso"
    -
      name: "medium"
      username: "mcomisso"
      url: "https://medium.com/@mcomisso"

# Permalinks
permalink: /:year/:month/:day/:title

excerpt_separator: <!--more-->

###############
# Site params #
###############
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

theme: minima
theme_color: red

highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

# Files to exclude, generic
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json
  - post.py
  - keybase.txt
