gems:
  - jekyll-sitemap
  - emoji_for_jekyll
  - kramdown
  - jekyll-gist
  - jekyll-paginate
  - jekyll-time-to-read

# permalink: /blog/:year/:month/:title
language: en

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

version:
  maj: 0
  min: 0
  build: 1

paginate: 5
paginate_path: "/blog/page:num/"
