##################
# Active plugins #
##################
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-paginate
# jekyll-mentions
# jemoji

# jekyll-seo-tag
# jekyll-gist
# jemoji

############
# Generics #
############
language: en
url: "http://mcomisso.xyz"
title: "Matteo Comisso"

author:
  name: "Matteo Comisso"
  email: "matteo.comisso@me.com"
  uri: "https://twitter.com/teomatteo89"
  avatar: "/assets/img/m-icon-white-on-blue.png"
  bio: ""
  services:
    -
      name: "github"
      username: "mcomisso"
      url: "https://github.com/mcomisso"
    -
      name: "twitter"
      username: "@teomatteo89"
      url: "https://twitter.com/teomatteo89"
    -
      name: "facebook"
      username: "matteocomisso"
      url: "https://facebook.com/100003457918621"
    -
      name: "linkedin"
      username: "mcomisso"
      url: "https://linkedin.com/mcomisso"
    -
      name: "google-plus"
      username: "+Matteocomisso"
      url: "https://plus.google.com/u/0/+Matteocomisso"
    -
      name: "medium"
      username: "@mcomisso"
      url: "https://medium.com/@mcomisso"

#Projects Data
projects:
  past:
    -
      name: "Blue-Mate"
      site: "/projects/blue-mate"
      description: "Startup focused on iBeacon, restaurants and proximity marketing campaigns."
    -
      name: "test"
      site: ""
      description: ""
  current:
    -
      name: "Personal Blog"
      site: "#"
      description: "This site. Built with Jekyll, material design lite and hosted on Github Pages."
    -
      name: "Architectures"
      site: ""
      description: "Exploring different mobile application architectures."

# Permalinks
permalink: /:year/:month/:day/:title
paginate_path: "/blog/page:num/"
paginate: 5

excerpt_separator: <!--more-->

###############
# Site params #
###############
google_analytics_id: "UA-73383879-1"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

version: 0.0.1

# Files to exclude, generic
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json
