##################
# Active plugins #
##################
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed

- jekyll-paginate

############
# Generics #
############
language: en
url: "https://mcomisso.github.io"

author:
  name: "Matteo Comisso"
  email: "matteo.comisso@me.com"
  uri: "https://twitter.com/teomatteo89"
  avatar: "/assets/img/m-icon-white-on-blue.png"
  bio: ""
  facebook: "matteocomisso"
  fb_id: 100003457918621
  twitter: "@teomatteo89"
  github: "mcomisso"
  google: "teomatteo89"


# Permalinks
permalink: /:year/:title
paginate_path: "/blog/page:num/"
paginate: 5


###############
# Site params #
###############
google_analytics_id: "UA-73383879-1"
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

version:
  maj: 0
  min: 0
  build: 1

# Files to exclude
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - src
  - node_modules
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json
